//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandelbrotDrawer.MandelbrotCalcServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MandelbrotWcfServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MandelbrotCalcServiceReference.IMandelbrotCalc")]
    public interface IMandelbrotCalc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/GetData", ReplyAction="http://tempuri.org/IMandelbrotCalc/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/GetData", ReplyAction="http://tempuri.org/IMandelbrotCalc/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/DrawMandelbrot", ReplyAction="http://tempuri.org/IMandelbrotCalc/DrawMandelbrotResponse")]
        System.Collections.Generic.List<System.IO.MemoryStream> DrawMandelbrot(int width, int height, System.Collections.Generic.List<System.Collections.Generic.List<double>> Scales, int numberOfIterations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/DrawMandelbrot", ReplyAction="http://tempuri.org/IMandelbrotCalc/DrawMandelbrotResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.IO.MemoryStream>> DrawMandelbrotAsync(int width, int height, System.Collections.Generic.List<System.Collections.Generic.List<double>> Scales, int numberOfIterations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMandelbrotCalc/GetDataUsingDataContractResponse")]
        MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType GetDataUsingDataContract(MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMandelbrotCalc/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType> GetDataUsingDataContractAsync(MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/InformAboutConnection", ReplyAction="http://tempuri.org/IMandelbrotCalc/InformAboutConnectionResponse")]
        void InformAboutConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMandelbrotCalc/InformAboutConnection", ReplyAction="http://tempuri.org/IMandelbrotCalc/InformAboutConnectionResponse")]
        System.Threading.Tasks.Task InformAboutConnectionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMandelbrotCalcChannel : MandelbrotDrawer.MandelbrotCalcServiceReference.IMandelbrotCalc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MandelbrotCalcClient : System.ServiceModel.ClientBase<MandelbrotDrawer.MandelbrotCalcServiceReference.IMandelbrotCalc>, MandelbrotDrawer.MandelbrotCalcServiceReference.IMandelbrotCalc {
        
        public MandelbrotCalcClient() {
        }
        
        public MandelbrotCalcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MandelbrotCalcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MandelbrotCalcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MandelbrotCalcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Collections.Generic.List<System.IO.MemoryStream> DrawMandelbrot(int width, int height, System.Collections.Generic.List<System.Collections.Generic.List<double>> Scales, int numberOfIterations) {
            return base.Channel.DrawMandelbrot(width, height, Scales, numberOfIterations);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.IO.MemoryStream>> DrawMandelbrotAsync(int width, int height, System.Collections.Generic.List<System.Collections.Generic.List<double>> Scales, int numberOfIterations) {
            return base.Channel.DrawMandelbrotAsync(width, height, Scales, numberOfIterations);
        }
        
        public MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType GetDataUsingDataContract(MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType> GetDataUsingDataContractAsync(MandelbrotDrawer.MandelbrotCalcServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void InformAboutConnection() {
            base.Channel.InformAboutConnection();
        }
        
        public System.Threading.Tasks.Task InformAboutConnectionAsync() {
            return base.Channel.InformAboutConnectionAsync();
        }
    }
}
